builds:
  - id: importer
    binary: importer
    main: ./cmd/importer/main.go
    hooks:
      pre: ./tools/prep-release.sh
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

brews:
  - name: importer
    tap:
      owner: upsidr
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/upsidr/importer
    description: Import any lines, from anywhere
