builds:
  - id: importer
    binary: importer
    main: ./cmd/importer/main.go
    env:
      - CGO_ENABLED=0
    hooks:
      pre: ./tools/prep-release.sh {{ .Tag }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"

brews:
  - name: importer
    tap:
      owner: upsidr
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/upsidr/importer
    description: Import any lines, from anywhere
