apiVersion: v1
kind: Service
metadata:
  name: color-svc
  labels:
    # == import: labels / begin from: snippets.yaml#[labels] indent: align ==
    app.kubernetes.io/name: color-svc
    app.kubernetes.io/version: v1
    # == import: labels / end ==
spec:
  ports:
    - name: http
      port: 8800
      targetPort: 8800
