name: Build

on:
  push:
    branches:
      - main
      - initial-implementation # For testing

jobs:
  build:
    name: Build Importer Binary
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.2

      - name: Build
        run: |
          go mod download
          go build ./cmd/importer/
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: importer
          path: ./importer
