name: Run Importer for Markdowns

on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: 1.16.5

jobs:
  importer:
    name: Run Importer Generate
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # NOTE: This is not using the published Importer as we want to ensure the
      #       new behaviour, but for common use cases, you can set up the below
      #       step to have Importer ready to be executed for your actions.
      # - name: Install Importer
      #   run: brew install upsidr/tap/importer

      # Build Importer
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run Go Build
        run: go build ./cmd/importer/

      - name: Run Importer against README.md
        run: ./importer generate README.md # This uses locally built Importer, take of `./` for usual use cases
      - name: Check if README.md has any change compared to the branch
        run: |
          git status --short
          git diff-index --quiet HEAD
